title = "Symentis"
titleSeparator = "-"
titleAddition = "Szkolenia wydajność aplikacji Java"
description = "Szkolenia - wydajność aplikacji Java z wykorzystaniem Java Microbenchmark Harness (JMH), Java Flight Recorder, async profiler."

images = ["images/56965449_q2968395883185766_2731928778866425856_n.jpg"]

twitterSite = "@j_palka"
twitterCreator = "@j_palka"
facebookAuthor = "verlinde.henk"
facebookPublisher = "verlinde.henk"
ogLocale = "pl"

schemaType = "Organization"
schemaLogo = "images/logo.svg"
schemaTwitter = "https://twitter.com/j_palka"
schemaLinkedIn = "https://www.linkedin.com/in/jpalka/"
schemaGitHub = "https://github.com/symentispl"
schemaSection = "blog"

siteLinksSearchBox = false

themeColor = "#fff"

quality = 85
bgColor = "#fff"
landscapePhotoWidths = [1000, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://gethyas.com/\">Hyas</a>"

alert = false
alertText = "Deliver web projects 10x faster. <a class=\"alert-link\" href=\"https://www.netlify.com/whitepaper/\" target=\"_blank\" rel=\"noopener\">Get the free enterprise paper →</a>"
